#!/bin/bash

set -ex

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

mkdir -p src/github.com/julz
mkdir -p src/github.com/opencontainers
ln -s $PWD/kardigan $GOPATH/src/github.com/julz/kardigan
ln -s $PWD/kardigan/dep/runc $GOPATH/src/github.com/opencontainers/runc
cd src/github.com/julz/kardigan

go get github.com/onsi/ginkgo/ginkgo

pushd $GOPATH/src/github.com/opencontainers/runc
  GOPATH=$PWD/Godeps/_workspace:$GOPATH go build -tags "seccomp apparmor" --ldflags '-extldflags "-static"' -o runc .
  cp runc /usr/local/bin/runc
popd

rm $GOPATH/src/github.com/opencontainers/runc

ginkgo test
